version: "3.8"

# Local development infrastructure for Cafe POS
# Runs databases and supporting services; run the Laravel app on the host (Windows) or via Sail if preferred.

services:
  mysql:
    image: mysql:8.0
    container_name: cafe_pos_mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode=STRICT_ALL_TABLES"]
    environment:
      MYSQL_DATABASE: cafe_pos
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # host:container (avoid clashing with local MySQL on 3306)
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cafe_pos_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cafe_pos_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI http://localhost:8025

  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: cafe_pos_meilisearch
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    profiles:
      - optional

volumes:
  mysql_data:
  redis_data:
  meili_data:
